### ISSUE TITLE
Call Limit 50 bei Hopify

### ISSUE THREAD

**Issue by merconic** [StefanOstwald/shopify-wolanski-fulfillment#3]
@StefanOstwald Gibt es eine Möglichkeit den GET Request so umzubauen, dass man nicht gegen das 50 API Calls Limit bei shopify läuft? VG Michael

**Comment by StefanOstwald** [comment]
Hallo @merconic ,
ja, dies ist bestimmt möglich. Zeitlich kann ich selber dies aktuell nicht leisten. Du kannst jedoch gerne einen Pull Request erstellen.
Viele Grüße
Stefan
